---
project_name: brushings_Immune
input_matrix: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/raw/cellranger/aggr/Immune/outs/aggregation.csv"
metadata: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024//brushings_all/results/qcontrol/brushings_Immune//metadata_prefilter.rds"
output_dir: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024//brushings_all/results/doubdet/Immune"
filters:
  score: 0.3
  doublet_rate: 0.06
vars:
  library: origlib
  class: orig.HT_ID.global
  dims: umap
do_parallel: no
...
