---
project_name: brushings_Ephi_clean2_good2
# path to the Cell Ranger ouput; it can even be a CSV file like the one in a Cell Ranger aggregation
input_expression: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/raw/cellranger/aggr/Ephi"
# A table of the metadata per library, or the whole metadata ready.
# It can be multiple files: [metadata_lib.csv, demultiplexed_hashtags.rdata]
metadata:
  - "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/results/clustering/brushings_Ephi_clean1/.object_meta.data_seurat_mean0.01_pct20_pc20.rds"
# if you don't add "/" at the end, it will append 'project_name'
output_dir: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/results/clustering"
filtering:
  subset:
    expr: "nFeature_RNA >= 200 & nFeature_RNA <= 5000 & nCount_RNA >= 300 & nCount_RNA <= 20000 & percent.mt <= 30"
    expre: "doublet_scores <= 0.3"
    expree: "orig.HT_ID.global %in% c('Singlet')"
    expreee: "!RNA_snn_res.0.1 %in% c(5,6)"
  nSamples_expressed: 0.001 # % of cells in which that gene is present
regress_var: [nCount_RNA, percent.mt]
norm: LogNormalize
variable_features:
  #file: ./data/prot_coding_genes.csv
  method: vst
  nfeatures: 2000
  percent: [15, 20, 25]  # iterated
  mean.cutoff: [0.01, 8]
  dispersion.cutoff: [1, Inf]
resolution: [0.1, 0.2, 0.3, 0.4, 0.6, 0.8] # iterated during markers
dim_reduction:
  base: {type: harmony, batch: "orig.run", n_comp: 40, chosen_comp: [15,20,25]} # iterated: chosen
  tsne: {perplexity: 'auto', reduction.use: "pca"}
  umap: {n.neighbors: 30, min.dist: 0.1}
markers:
  select: snn_res. # pattern in the metadata's columns
  test: MAST
  avg_logFC: 0.25
  p_val_adj: 0.05
tool: seurat
exec: /mnt/hpc-apps/R/4.1.3/bin/Rscript
script: /home/fcastaneda/bin/clustering/R/seurat.R
pipeline: /home/fcastaneda/bin/clustering/
cluster_config: /home/fcastaneda/bin/clustering/cluster_slurm.json
environment: clustering_new
...
