---
project_name: brushings_Ephi
# it can even be a CSV file like the one in a Cell Ranger aggregation
input_expression: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/raw/cellranger/aggr/Ephi"
# A table of the metadata per library, or the whole metadata ready
# it can be multiple file
metadata: ["/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/info/metadata_library.csv", "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/brushings_all/results/ab_capture/brushings_all/Ephi.rds"]
# if you don't add "/" at the end, it will append 'project_name'
output_dir: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024//brushings_all/results/qcontrol/"
# A file will sufice; columns must be metrics names in the metadata
filtering:
  #file: "./data/file.csv"
  nFeature_RNA: [200, 2000, 1]
  nCount_RNA: [400, 20000, 1]
  percent.mt: [0, 15, 1] 
  expr: "!(orig.HT_ID.global %in% c('Negative', 'Doublet') | is.na(orig.HT_ID.global))"
...
