---
project_name: biop_CD45N
# it can even be a CSV file like the one in a Cell Ranger aggregation
input_expression: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/biop/raw/cellranger/aggr/CD45N/outs/aggregation.csv"
# A table of the metadata per library, or the whole metadata ready
# it can be multiple file
metadata: ["/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/biop/info/metadata_library.csv", "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/biop/results/ab_capture/biop/CD45N.rds"]
# if you don't add "/" at the end, it will append 'project_name'
output_dir: "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024//biop/results/qcontrol/"
# A file will sufice; columns must be metrics names in the metadata
filtering:
  #file: "./data/file.csv"
  nFeature_RNA: [200, 5000, 1]
  nCount_RNA: [300, 20000, 1]
  percent.mt: [0, 30, 1] 
  expr: (!(orig.HT_ID.global %in% c('Negative', 'Doublet')) & !is.na(orig.HT_ID.global))
...
